### PR TITLE
Update TUTORIAL.md

### PR DESCRIPTION
**Pull request by RikLubbers**

### CODE REVIEW

**Review by ptimoner — CHANGES_REQUESTED** [review]
Thanks Rik,
Maybe for avoiding the extra indentation, you can put the following, without any indentation. I will then approve the pull request.
```r
process_inputs(mainPath, country, selectedInputs = "All", mostRecent = TRUE, alwaysProcess = TRUE, defaultMethods = TRUE, changeRes = TRUE, newRes = 100, popCorrection = TRUE, gridRes = 3000)
```

**Comment by RikLubbers** [comment]
Hi P.,

I added a '---' as otherwise a single indent is not recognized as a code block due to the list above.

**Review by ptimoner — CHANGES_REQUESTED** [review]
Sorry. I was suggesting to put the code between \`\`\`r and \`\`\` but I didn't escape the \` symbols and it's been interpreted as code block in the conversation. My bad. So my solution would be as following, with no need to add a line.
\`\`\`r
process_inputs(mainPath, country, selectedInputs = "All", mostRecent = TRUE, alwaysProcess = TRUE, defaultMethods = TRUE, changeRes = TRUE, newRes = 100, popCorrection = TRUE, gridRes = 3000)
\`\`\`
I will wait for your new pull request.

Thanks again.

**Comment by RikLubbers** [comment]
Ah yes, I was contemplating if that was what you meant. I have updated it.

**Review by ptimoner — APPROVED** [review]
Great, thanks !

**Pull request merged**
